// Generated by aileron-codegen — do not edit.
//
// Re-run `task generate` to refresh after changing the spec or
// gen.yaml.

package main

import (
	"encoding/json"
	"errors"
	"fmt"
	"io"
)

// input is the JSON envelope the Aileron runtime writes to stdin
// when invoking the connector.
type input struct {
	Op   string         `json:"op"`
	Args map[string]any `json:"args"`
}

// output is the JSON envelope the connector writes back on stdout.
// Output is populated on success, Error on failure; exactly one.
type output struct {
	Output map[string]any `json:"output,omitempty"`
	Error  *outputError   `json:"error,omitempty"`
}

type outputError struct {
	Class   string `json:"class"`
	Message string `json:"message"`
}

// Transport sends one Aileron-host HTTP request envelope and returns
// (body, status, err). The wasip1 build provides the real
// implementation via host imports; non-wasip1 builds use an
// always-fail stub or a test mock.
type Transport func(payload []byte) ([]byte, int, error)

// knownOps is the set of op names the connector dispatches. Kept in
// lock-step with handlers.go's per-op handler functions by codegen.
var knownOps = map[string]bool{
	"comment_create": true,
	"issue":          true,
	"issue_create":   true,
	"viewer":         true,
}

// run is the testable seam under main(). Reads one JSON op dispatch
// from stdin, drives the chosen handler against the supplied
// Transport, writes one JSON result envelope to stdout. Returns the
// process exit code.
func run(stdin io.Reader, stdout io.Writer, transport Transport) int {
	raw, err := io.ReadAll(stdin)
	if err != nil {
		writeError(stdout, "connector_runtime_error", "read_stdin: "+err.Error())
		return 1
	}
	var in input
	if err := json.Unmarshal(raw, &in); err != nil {
		writeError(stdout, "connector_runtime_error", "parse_input: "+err.Error())
		return 1
	}
	if !knownOps[in.Op] {
		writeError(stdout, "unknown_op", "op "+in.Op+" is not exposed by this connector")
		return 1
	}
	data, err := handle(in.Op, in.Args, transport)
	if err != nil {
		writeError(stdout, classify(err), err.Error())
		return 1
	}
	writeSuccess(stdout, data)
	return 0
}

// handle dispatches one op to its handler. The caller must have
// already validated that op is in knownOps.
func handle(op string, args map[string]any, transport Transport) (map[string]any, error) {
	switch op {
	case "comment_create":
		return handleCommentCreate(args, transport)
	case "issue":
		return handleIssue(args, transport)
	case "issue_create":
		return handleIssueCreate(args, transport)
	case "viewer":
		return handleViewer(args, transport)
	}
	return nil, fmt.Errorf("unhandled op %q", op)
}

func writeError(w io.Writer, class, message string) {
	out := output{Error: &outputError{Class: class, Message: message}}
	_ = json.NewEncoder(w).Encode(out)
}

func writeSuccess(w io.Writer, payload map[string]any) {
	out := output{Output: payload}
	_ = json.NewEncoder(w).Encode(out)
}

// classify maps a handler error into the Aileron error class string.
// Non-GraphQL errors funnel to `connector_runtime_error`; a
// `*graphqlErrors` (HTTP 200 with non-empty errors[]) gets its
// own class so callers can distinguish.
func classify(err error) string {
	var graphqlErr *graphqlErrors
	if errors.As(err, &graphqlErr) {
		return "graphql_error"
	}
	return "connector_runtime_error"
}
