// Generated by aileron-codegen — do not edit.
//
// Re-run `task generate` to refresh after changing the spec or
// gen.yaml.

package main

import (
	"encoding/json"
	"errors"
	"fmt"
	"io"
)

// input is the JSON envelope the Aileron runtime writes to stdin
// when invoking the connector.
type input struct {
	Op   string         `json:"op"`
	Args map[string]any `json:"args"`
}

// output is the JSON envelope the connector writes back on stdout.
// Output is populated on success, Error on failure; exactly one.
type output struct {
	Output map[string]any `json:"output,omitempty"`
	Error  *outputError   `json:"error,omitempty"`
}

type outputError struct {
	Class   string `json:"class"`
	Message string `json:"message"`
}

// Transport sends one Aileron-host HTTP request envelope and returns
// (body, status, err). The wasip1 build provides the real
// implementation via host imports; non-wasip1 builds use an
// always-fail stub or a test mock.
type Transport func(payload []byte) ([]byte, int, error)

// knownOps is the set of op names the connector dispatches. Kept in
// lock-step with handlers.go's per-op handler functions by codegen.
var knownOps = map[string]bool{
	"administrable_teams":                               true,
	"agent_activities":                                  true,
	"agent_activity":                                    true,
	"agent_activity_create":                             true,
	"agent_activity_create_prompt":                      true,
	"agent_activity_created":                            true,
	"agent_activity_delete_queued":                      true,
	"agent_activity_send_queued":                        true,
	"agent_activity_updated":                            true,
	"agent_session":                                     true,
	"agent_session_create":                              true,
	"agent_session_create_on_comment":                   true,
	"agent_session_create_on_issue":                     true,
	"agent_session_created":                             true,
	"agent_session_sandbox":                             true,
	"agent_session_update":                              true,
	"agent_session_update_external_url":                 true,
	"agent_session_updated":                             true,
	"agent_sessions":                                    true,
	"ai_conversation_updated":                           true,
	"ai_prompt_progress_created":                        true,
	"ai_prompt_progress_updated":                        true,
	"airbyte_integration_connect":                       true,
	"application_info":                                  true,
	"archived_integrations":                             true,
	"archived_teams":                                    true,
	"attachment":                                        true,
	"attachment_create":                                 true,
	"attachment_delete":                                 true,
	"attachment_issue":                                  true,
	"attachment_link_discord":                           true,
	"attachment_link_front":                             true,
	"attachment_link_git_hub_issue":                     true,
	"attachment_link_git_hub_p_r":                       true,
	"attachment_link_git_lab_m_r":                       true,
	"attachment_link_intercom":                          true,
	"attachment_link_jira_issue":                        true,
	"attachment_link_salesforce":                        true,
	"attachment_link_slack":                             true,
	"attachment_link_u_r_l":                             true,
	"attachment_link_zendesk":                           true,
	"attachment_sources":                                true,
	"attachment_sync_to_slack":                          true,
	"attachment_update":                                 true,
	"attachments":                                       true,
	"attachments_for_u_r_l":                             true,
	"audit_entries":                                     true,
	"audit_entry_types":                                 true,
	"authentication_sessions":                           true,
	"available_users":                                   true,
	"comment":                                           true,
	"comment_archived":                                  true,
	"comment_create":                                    true,
	"comment_created":                                   true,
	"comment_delete":                                    true,
	"comment_deleted":                                   true,
	"comment_resolve":                                   true,
	"comment_unarchived":                                true,
	"comment_unresolve":                                 true,
	"comment_update":                                    true,
	"comment_updated":                                   true,
	"comments":                                          true,
	"contact_create":                                    true,
	"contact_sales_create":                              true,
	"create_csv_export_report":                          true,
	"create_initiative_update_reminder":                 true,
	"create_organization_from_onboarding":               true,
	"create_project_update_reminder":                    true,
	"custom_view":                                       true,
	"custom_view_create":                                true,
	"custom_view_delete":                                true,
	"custom_view_details_suggestion":                    true,
	"custom_view_has_subscribers":                       true,
	"custom_view_update":                                true,
	"custom_views":                                      true,
	"customer":                                          true,
	"customer_create":                                   true,
	"customer_delete":                                   true,
	"customer_merge":                                    true,
	"customer_need":                                     true,
	"customer_need_archive":                             true,
	"customer_need_create":                              true,
	"customer_need_create_from_attachment":              true,
	"customer_need_delete":                              true,
	"customer_need_unarchive":                           true,
	"customer_need_update":                              true,
	"customer_needs":                                    true,
	"customer_status":                                   true,
	"customer_status_create":                            true,
	"customer_status_delete":                            true,
	"customer_status_update":                            true,
	"customer_statuses":                                 true,
	"customer_tier":                                     true,
	"customer_tier_create":                              true,
	"customer_tier_delete":                              true,
	"customer_tier_update":                              true,
	"customer_tiers":                                    true,
	"customer_unsync":                                   true,
	"customer_update":                                   true,
	"customer_upsert":                                   true,
	"customers":                                         true,
	"cycle":                                             true,
	"cycle_archive":                                     true,
	"cycle_archived":                                    true,
	"cycle_create":                                      true,
	"cycle_created":                                     true,
	"cycle_shift_all":                                   true,
	"cycle_start_upcoming_cycle_today":                  true,
	"cycle_update":                                      true,
	"cycle_updated":                                     true,
	"cycles":                                            true,
	"document":                                          true,
	"document_archived":                                 true,
	"document_content_created":                          true,
	"document_content_draft_created":                    true,
	"document_content_draft_deleted":                    true,
	"document_content_draft_updated":                    true,
	"document_content_history":                          true,
	"document_content_history_entries":                  true,
	"document_content_history_timeline":                 true,
	"document_content_updated":                          true,
	"document_create":                                   true,
	"document_created":                                  true,
	"document_delete":                                   true,
	"document_unarchive":                                true,
	"document_unarchived":                               true,
	"document_update":                                   true,
	"document_updated":                                  true,
	"documents":                                         true,
	"draft_created":                                     true,
	"draft_deleted":                                     true,
	"draft_updated":                                     true,
	"dummy":                                             true,
	"email_intake_address":                              true,
	"email_intake_address_create":                       true,
	"email_intake_address_delete":                       true,
	"email_intake_address_rotate":                       true,
	"email_intake_address_update":                       true,
	"email_token_user_account_auth":                     true,
	"email_unsubscribe":                                 true,
	"email_user_account_auth_challenge":                 true,
	"emoji":                                             true,
	"emoji_create":                                      true,
	"emoji_delete":                                      true,
	"emojis":                                            true,
	"entity_external_link":                              true,
	"entity_external_link_create":                       true,
	"entity_external_link_delete":                       true,
	"entity_external_link_update":                       true,
	"external_user":                                     true,
	"external_users":                                    true,
	"failures_for_oauth_webhooks":                       true,
	"favorite":                                          true,
	"favorite_create":                                   true,
	"favorite_created":                                  true,
	"favorite_delete":                                   true,
	"favorite_deleted":                                  true,
	"favorite_update":                                   true,
	"favorite_updated":                                  true,
	"favorites":                                         true,
	"fetch_data":                                        true,
	"file_upload":                                       true,
	"file_upload_dangerously_delete":                    true,
	"git_automation_state_create":                       true,
	"git_automation_state_delete":                       true,
	"git_automation_state_update":                       true,
	"git_automation_target_branch_create":               true,
	"git_automation_target_branch_delete":               true,
	"git_automation_target_branch_update":               true,
	"google_user_account_auth":                          true,
	"image_upload_from_url":                             true,
	"import_file_upload":                                true,
	"initiative":                                        true,
	"initiative_add_label":                              true,
	"initiative_archive":                                true,
	"initiative_create":                                 true,
	"initiative_created":                                true,
	"initiative_delete":                                 true,
	"initiative_deleted":                                true,
	"initiative_relation":                               true,
	"initiative_relation_create":                        true,
	"initiative_relation_delete":                        true,
	"initiative_relation_update":                        true,
	"initiative_relations":                              true,
	"initiative_remove_label":                           true,
	"initiative_to_project":                             true,
	"initiative_to_project_create":                      true,
	"initiative_to_project_delete":                      true,
	"initiative_to_project_update":                      true,
	"initiative_to_projects":                            true,
	"initiative_unarchive":                              true,
	"initiative_update":                                 true,
	"initiative_update_archive":                         true,
	"initiative_update_create":                          true,
	"initiative_update_mutation":                        true,
	"initiative_update_unarchive":                       true,
	"initiative_update_update":                          true,
	"initiative_updated":                                true,
	"initiative_updates":                                true,
	"initiatives":                                       true,
	"integration":                                       true,
	"integration_archive":                               true,
	"integration_asks_connect_channel":                  true,
	"integration_customer_data_attributes_refresh":      true,
	"integration_delete":                                true,
	"integration_discord":                               true,
	"integration_figma":                                 true,
	"integration_front":                                 true,
	"integration_git_hub_enterprise_server_connect":     true,
	"integration_git_hub_personal":                      true,
	"integration_github_commit_create":                  true,
	"integration_github_connect":                        true,
	"integration_github_import_connect":                 true,
	"integration_github_import_refresh":                 true,
	"integration_github_remove_code_access":             true,
	"integration_gitlab_connect":                        true,
	"integration_gitlab_test_connection":                true,
	"integration_gong":                                  true,
	"integration_google_calendar_personal_connect":      true,
	"integration_google_sheets":                         true,
	"integration_has_scopes":                            true,
	"integration_intercom":                              true,
	"integration_intercom_delete":                       true,
	"integration_intercom_settings_update":              true,
	"integration_jira_fetch_project_statuses":           true,
	"integration_jira_personal":                         true,
	"integration_jira_update":                           true,
	"integration_launch_darkly_connect":                 true,
	"integration_launch_darkly_personal_connect":        true,
	"integration_loom":                                  true,
	"integration_mcp_server_connect":                    true,
	"integration_mcp_server_personal_connect":           true,
	"integration_microsoft_personal_connect":            true,
	"integration_microsoft_teams":                       true,
	"integration_microsoft_teams_project_post":          true,
	"integration_opsgenie_connect":                      true,
	"integration_opsgenie_refresh_schedule_mappings":    true,
	"integration_pager_duty_connect":                    true,
	"integration_pager_duty_refresh_schedule_mappings":  true,
	"integration_request":                               true,
	"integration_salesforce":                            true,
	"integration_salesforce_metadata_refresh":           true,
	"integration_sentry_connect":                        true,
	"integration_settings_update":                       true,
	"integration_slack":                                 true,
	"integration_slack_asks":                            true,
	"integration_slack_custom_view_notifications":       true,
	"integration_slack_customer_channel_link":           true,
	"integration_slack_import_emojis":                   true,
	"integration_slack_initiative_post":                 true,
	"integration_slack_or_asks_update_slack_team_name":  true,
	"integration_slack_org_initiative_updates_post":     true,
	"integration_slack_org_project_updates_post":        true,
	"integration_slack_personal":                        true,
	"integration_slack_post":                            true,
	"integration_slack_project_post":                    true,
	"integration_slack_workflow_access_update":          true,
	"integration_template":                              true,
	"integration_template_create":                       true,
	"integration_template_delete":                       true,
	"integration_templates":                             true,
	"integration_update":                                true,
	"integration_zendesk":                               true,
	"integrations":                                      true,
	"integrations_settings":                             true,
	"integrations_settings_create":                      true,
	"integrations_settings_update":                      true,
	"issue":                                             true,
	"issue_add_label":                                   true,
	"issue_archive":                                     true,
	"issue_archived":                                    true,
	"issue_batch_create":                                true,
	"issue_batch_update":                                true,
	"issue_create":                                      true,
	"issue_created":                                     true,
	"issue_delete":                                      true,
	"issue_description_update_from_front":               true,
	"issue_draft_created":                               true,
	"issue_draft_deleted":                               true,
	"issue_draft_updated":                               true,
	"issue_external_sync_disable":                       true,
	"issue_figma_file_key_search":                       true,
	"issue_filter_suggestion":                           true,
	"issue_history_created":                             true,
	"issue_history_updated":                             true,
	"issue_import_check_c_s_v":                          true,
	"issue_import_check_sync":                           true,
	"issue_import_create_asana":                         true,
	"issue_import_create_c_s_v_jira":                    true,
	"issue_import_create_clubhouse":                     true,
	"issue_import_create_github":                        true,
	"issue_import_create_jira":                          true,
	"issue_import_create_linear_v2":                     true,
	"issue_import_delete":                               true,
	"issue_import_jql_check":                            true,
	"issue_import_process":                              true,
	"issue_import_update":                               true,
	"issue_label":                                       true,
	"issue_label_create":                                true,
	"issue_label_created":                               true,
	"issue_label_delete":                                true,
	"issue_label_deleted":                               true,
	"issue_label_restore":                               true,
	"issue_label_retire":                                true,
	"issue_label_update":                                true,
	"issue_label_updated":                               true,
	"issue_labels":                                      true,
	"issue_priority_values":                             true,
	"issue_relation":                                    true,
	"issue_relation_create":                             true,
	"issue_relation_created":                            true,
	"issue_relation_delete":                             true,
	"issue_relation_deleted":                            true,
	"issue_relation_update":                             true,
	"issue_relation_updated":                            true,
	"issue_relations":                                   true,
	"issue_reminder":                                    true,
	"issue_remove_label":                                true,
	"issue_repository_suggestions":                      true,
	"issue_search":                                      true,
	"issue_share":                                       true,
	"issue_subscribe":                                   true,
	"issue_title_suggestion_from_customer_request":      true,
	"issue_to_release":                                  true,
	"issue_to_release_create":                           true,
	"issue_to_release_delete":                           true,
	"issue_to_release_delete_by_issue_and_release":      true,
	"issue_to_releases":                                 true,
	"issue_unarchive":                                   true,
	"issue_unarchived":                                  true,
	"issue_unshare":                                     true,
	"issue_unsubscribe":                                 true,
	"issue_update":                                      true,
	"issue_updated":                                     true,
	"issue_vcs_branch_search":                           true,
	"issues":                                            true,
	"jira_integration_connect":                          true,
	"join_organization_from_onboarding":                 true,
	"latest_release_by_access_key":                      true,
	"leave_organization":                                true,
	"logout":                                            true,
	"logout_all_sessions":                               true,
	"logout_other_sessions":                             true,
	"logout_session":                                    true,
	"microsoft_teams_channels":                          true,
	"notification":                                      true,
	"notification_archive":                              true,
	"notification_archive_all":                          true,
	"notification_archived":                             true,
	"notification_category_channel_subscription_update": true,
	"notification_created":                              true,
	"notification_deleted":                              true,
	"notification_mark_read_all":                        true,
	"notification_mark_unread_all":                      true,
	"notification_snooze_all":                           true,
	"notification_subscription":                         true,
	"notification_subscription_create":                  true,
	"notification_subscription_delete":                  true,
	"notification_subscription_update":                  true,
	"notification_subscriptions":                        true,
	"notification_unarchive":                            true,
	"notification_unarchived":                           true,
	"notification_unsnooze_all":                         true,
	"notification_update":                               true,
	"notification_updated":                              true,
	"notifications":                                     true,
	"notifications_unread_count":                        true,
	"oauth_application":                                 true,
	"oauth_application_archive":                         true,
	"oauth_application_create":                          true,
	"oauth_application_rotate_secret":                   true,
	"oauth_application_rotate_webhook_secret":           true,
	"oauth_application_update":                          true,
	"oauth_applications":                                true,
	"organization":                                      true,
	"organization_cancel_delete":                        true,
	"organization_delete":                               true,
	"organization_delete_challenge":                     true,
	"organization_domain_claim":                         true,
	"organization_domain_claim_request":                 true,
	"organization_domain_create":                        true,
	"organization_domain_delete":                        true,
	"organization_domain_update":                        true,
	"organization_domain_verify":                        true,
	"organization_exists":                               true,
	"organization_invite":                               true,
	"organization_invite_create":                        true,
	"organization_invite_delete":                        true,
	"organization_invite_details":                       true,
	"organization_invite_update":                        true,
	"organization_invites":                              true,
	"organization_meta":                                 true,
	"organization_start_trial":                          true,
	"organization_start_trial_for_plan":                 true,
	"organization_update":                               true,
	"organization_updated":                              true,
	"passkey_login_finish":                              true,
	"passkey_login_start":                               true,
	"project":                                           true,
	"project_add_label":                                 true,
	"project_archive":                                   true,
	"project_archived":                                  true,
	"project_create":                                    true,
	"project_create_slack_channel":                      true,
	"project_created":                                   true,
	"project_delete":                                    true,
	"project_external_sync_disable":                     true,
	"project_filter_suggestion":                         true,
	"project_label":                                     true,
	"project_label_create":                              true,
	"project_label_delete":                              true,
	"project_label_restore":                             true,
	"project_label_retire":                              true,
	"project_label_update":                              true,
	"project_labels":                                    true,
	"project_milestone":                                 true,
	"project_milestone_create":                          true,
	"project_milestone_delete":                          true,
	"project_milestone_move":                            true,
	"project_milestone_update":                          true,
	"project_milestones":                                true,
	"project_reassign_status":                           true,
	"project_relation":                                  true,
	"project_relation_create":                           true,
	"project_relation_delete":                           true,
	"project_relation_update":                           true,
	"project_relations":                                 true,
	"project_remove_label":                              true,
	"project_status":                                    true,
	"project_status_archive":                            true,
	"project_status_create":                             true,
	"project_status_project_count":                      true,
	"project_status_unarchive":                          true,
	"project_status_update":                             true,
	"project_statuses":                                  true,
	"project_unarchive":                                 true,
	"project_unarchived":                                true,
	"project_update":                                    true,
	"project_update_archive":                            true,
	"project_update_archived":                           true,
	"project_update_create":                             true,
	"project_update_created":                            true,
	"project_update_delete":                             true,
	"project_update_deleted":                            true,
	"project_update_mutation":                           true,
	"project_update_unarchive":                          true,
	"project_update_update":                             true,
	"project_update_updated":                            true,
	"project_updated":                                   true,
	"project_updates":                                   true,
	"projects":                                          true,
	"push_subscription_create":                          true,
	"push_subscription_delete":                          true,
	"push_subscription_test":                            true,
	"rate_limit_status":                                 true,
	"reaction_create":                                   true,
	"reaction_delete":                                   true,
	"recent_releases_by_access_key":                     true,
	"refresh_google_sheets_data":                        true,
	"release":                                           true,
	"release_archive":                                   true,
	"release_complete":                                  true,
	"release_complete_by_access_key":                    true,
	"release_create":                                    true,
	"release_delete":                                    true,
	"release_note":                                      true,
	"release_note_create":                               true,
	"release_note_delete":                               true,
	"release_note_update":                               true,
	"release_notes":                                     true,
	"release_pipeline":                                  true,
	"release_pipeline_archive":                          true,
	"release_pipeline_by_access_key":                    true,
	"release_pipeline_create":                           true,
	"release_pipeline_delete":                           true,
	"release_pipeline_unarchive":                        true,
	"release_pipeline_update":                           true,
	"release_pipelines":                                 true,
	"release_search":                                    true,
	"release_stage":                                     true,
	"release_stage_archive":                             true,
	"release_stage_create":                              true,
	"release_stage_unarchive":                           true,
	"release_stage_update":                              true,
	"release_stages":                                    true,
	"release_sync":                                      true,
	"release_sync_by_access_key":                        true,
	"release_unarchive":                                 true,
	"release_update":                                    true,
	"release_update_by_pipeline":                        true,
	"release_update_by_pipeline_by_access_key":          true,
	"releases":                                          true,
	"resend_organization_invite":                        true,
	"resend_organization_invite_by_email":               true,
	"roadmap":                                           true,
	"roadmap_archive":                                   true,
	"roadmap_create":                                    true,
	"roadmap_created":                                   true,
	"roadmap_delete":                                    true,
	"roadmap_deleted":                                   true,
	"roadmap_to_project":                                true,
	"roadmap_to_project_create":                         true,
	"roadmap_to_project_delete":                         true,
	"roadmap_to_project_update":                         true,
	"roadmap_to_projects":                               true,
	"roadmap_unarchive":                                 true,
	"roadmap_update":                                    true,
	"roadmap_updated":                                   true,
	"roadmaps":                                          true,
	"saml_token_user_account_auth":                      true,
	"search_documents":                                  true,
	"search_issues":                                     true,
	"search_projects":                                   true,
	"semantic_search":                                   true,
	"sla_configurations":                                true,
	"sso_url_from_email":                                true,
	"team":                                              true,
	"team_create":                                       true,
	"team_created":                                      true,
	"team_cycles_delete":                                true,
	"team_delete":                                       true,
	"team_deleted":                                      true,
	"team_key_delete":                                   true,
	"team_membership":                                   true,
	"team_membership_create":                            true,
	"team_membership_created":                           true,
	"team_membership_delete":                            true,
	"team_membership_deleted":                           true,
	"team_membership_update":                            true,
	"team_membership_updated":                           true,
	"team_memberships":                                  true,
	"team_unarchive":                                    true,
	"team_update":                                       true,
	"team_updated":                                      true,
	"teams":                                             true,
	"template":                                          true,
	"template_create":                                   true,
	"template_delete":                                   true,
	"template_update":                                   true,
	"templates":                                         true,
	"templates_for_integration":                         true,
	"time_schedule":                                     true,
	"time_schedule_create":                              true,
	"time_schedule_delete":                              true,
	"time_schedule_refresh_integration_schedule":        true,
	"time_schedule_update":                              true,
	"time_schedule_upsert_external":                     true,
	"time_schedules":                                    true,
	"track_anonymous_event":                             true,
	"triage_responsibilities":                           true,
	"triage_responsibility":                             true,
	"triage_responsibility_create":                      true,
	"triage_responsibility_delete":                      true,
	"triage_responsibility_update":                      true,
	"update_integration_slack_scopes":                   true,
	"user":                                              true,
	"user_change_role":                                  true,
	"user_created":                                      true,
	"user_discord_connect":                              true,
	"user_external_user_disconnect":                     true,
	"user_flag_update":                                  true,
	"user_revoke_all_sessions":                          true,
	"user_revoke_session":                               true,
	"user_sessions":                                     true,
	"user_settings":                                     true,
	"user_settings_flags_reset":                         true,
	"user_settings_update":                              true,
	"user_suspend":                                      true,
	"user_unlink_from_identity_provider":                true,
	"user_unsuspend":                                    true,
	"user_update":                                       true,
	"user_updated":                                      true,
	"users":                                             true,
	"verify_git_hub_enterprise_server_installation":     true,
	"view_preferences_create":                           true,
	"view_preferences_delete":                           true,
	"view_preferences_update":                           true,
	"viewer":                                            true,
	"webhook":                                           true,
	"webhook_create":                                    true,
	"webhook_delete":                                    true,
	"webhook_rotate_secret":                             true,
	"webhook_update":                                    true,
	"webhooks":                                          true,
	"workflow_state":                                    true,
	"workflow_state_archive":                            true,
	"workflow_state_archived":                           true,
	"workflow_state_create":                             true,
	"workflow_state_created":                            true,
	"workflow_state_update":                             true,
	"workflow_state_updated":                            true,
	"workflow_states":                                   true,
}

// run is the testable seam under main(). Reads one JSON op dispatch
// from stdin, drives the chosen handler against the supplied
// Transport, writes one JSON result envelope to stdout. Returns the
// process exit code.
func run(stdin io.Reader, stdout io.Writer, transport Transport) int {
	raw, err := io.ReadAll(stdin)
	if err != nil {
		writeError(stdout, "connector_runtime_error", "read_stdin: "+err.Error())
		return 1
	}
	var in input
	if err := json.Unmarshal(raw, &in); err != nil {
		writeError(stdout, "connector_runtime_error", "parse_input: "+err.Error())
		return 1
	}
	if !knownOps[in.Op] {
		writeError(stdout, "unknown_op", "op "+in.Op+" is not exposed by this connector")
		return 1
	}
	data, err := handle(in.Op, in.Args, transport)
	if err != nil {
		writeError(stdout, classify(err), err.Error())
		return 1
	}
	writeSuccess(stdout, data)
	return 0
}

// handle dispatches one op to its handler. The caller must have
// already validated that op is in knownOps.
func handle(op string, args map[string]any, transport Transport) (map[string]any, error) {
	switch op {
	case "administrable_teams":
		return handleAdministrableTeams(args, transport)
	case "agent_activities":
		return handleAgentActivities(args, transport)
	case "agent_activity":
		return handleAgentActivity(args, transport)
	case "agent_activity_create":
		return handleAgentActivityCreate(args, transport)
	case "agent_activity_create_prompt":
		return handleAgentActivityCreatePrompt(args, transport)
	case "agent_activity_created":
		return handleAgentActivityCreated(args, transport)
	case "agent_activity_delete_queued":
		return handleAgentActivityDeleteQueued(args, transport)
	case "agent_activity_send_queued":
		return handleAgentActivitySendQueued(args, transport)
	case "agent_activity_updated":
		return handleAgentActivityUpdated(args, transport)
	case "agent_session":
		return handleAgentSession(args, transport)
	case "agent_session_create":
		return handleAgentSessionCreate(args, transport)
	case "agent_session_create_on_comment":
		return handleAgentSessionCreateOnComment(args, transport)
	case "agent_session_create_on_issue":
		return handleAgentSessionCreateOnIssue(args, transport)
	case "agent_session_created":
		return handleAgentSessionCreated(args, transport)
	case "agent_session_sandbox":
		return handleAgentSessionSandbox(args, transport)
	case "agent_session_update":
		return handleAgentSessionUpdate(args, transport)
	case "agent_session_update_external_url":
		return handleAgentSessionUpdateExternalUrl(args, transport)
	case "agent_session_updated":
		return handleAgentSessionUpdated(args, transport)
	case "agent_sessions":
		return handleAgentSessions(args, transport)
	case "ai_conversation_updated":
		return handleAiConversationUpdated(args, transport)
	case "ai_prompt_progress_created":
		return handleAiPromptProgressCreated(args, transport)
	case "ai_prompt_progress_updated":
		return handleAiPromptProgressUpdated(args, transport)
	case "airbyte_integration_connect":
		return handleAirbyteIntegrationConnect(args, transport)
	case "application_info":
		return handleApplicationInfo(args, transport)
	case "archived_integrations":
		return handleArchivedIntegrations(args, transport)
	case "archived_teams":
		return handleArchivedTeams(args, transport)
	case "attachment":
		return handleAttachment(args, transport)
	case "attachment_create":
		return handleAttachmentCreate(args, transport)
	case "attachment_delete":
		return handleAttachmentDelete(args, transport)
	case "attachment_issue":
		return handleAttachmentIssue(args, transport)
	case "attachment_link_discord":
		return handleAttachmentLinkDiscord(args, transport)
	case "attachment_link_front":
		return handleAttachmentLinkFront(args, transport)
	case "attachment_link_git_hub_issue":
		return handleAttachmentLinkGitHubIssue(args, transport)
	case "attachment_link_git_hub_p_r":
		return handleAttachmentLinkGitHubPR(args, transport)
	case "attachment_link_git_lab_m_r":
		return handleAttachmentLinkGitLabMR(args, transport)
	case "attachment_link_intercom":
		return handleAttachmentLinkIntercom(args, transport)
	case "attachment_link_jira_issue":
		return handleAttachmentLinkJiraIssue(args, transport)
	case "attachment_link_salesforce":
		return handleAttachmentLinkSalesforce(args, transport)
	case "attachment_link_slack":
		return handleAttachmentLinkSlack(args, transport)
	case "attachment_link_u_r_l":
		return handleAttachmentLinkURL(args, transport)
	case "attachment_link_zendesk":
		return handleAttachmentLinkZendesk(args, transport)
	case "attachment_sources":
		return handleAttachmentSources(args, transport)
	case "attachment_sync_to_slack":
		return handleAttachmentSyncToSlack(args, transport)
	case "attachment_update":
		return handleAttachmentUpdate(args, transport)
	case "attachments":
		return handleAttachments(args, transport)
	case "attachments_for_u_r_l":
		return handleAttachmentsForURL(args, transport)
	case "audit_entries":
		return handleAuditEntries(args, transport)
	case "audit_entry_types":
		return handleAuditEntryTypes(args, transport)
	case "authentication_sessions":
		return handleAuthenticationSessions(args, transport)
	case "available_users":
		return handleAvailableUsers(args, transport)
	case "comment":
		return handleComment(args, transport)
	case "comment_archived":
		return handleCommentArchived(args, transport)
	case "comment_create":
		return handleCommentCreate(args, transport)
	case "comment_created":
		return handleCommentCreated(args, transport)
	case "comment_delete":
		return handleCommentDelete(args, transport)
	case "comment_deleted":
		return handleCommentDeleted(args, transport)
	case "comment_resolve":
		return handleCommentResolve(args, transport)
	case "comment_unarchived":
		return handleCommentUnarchived(args, transport)
	case "comment_unresolve":
		return handleCommentUnresolve(args, transport)
	case "comment_update":
		return handleCommentUpdate(args, transport)
	case "comment_updated":
		return handleCommentUpdated(args, transport)
	case "comments":
		return handleComments(args, transport)
	case "contact_create":
		return handleContactCreate(args, transport)
	case "contact_sales_create":
		return handleContactSalesCreate(args, transport)
	case "create_csv_export_report":
		return handleCreateCsvExportReport(args, transport)
	case "create_initiative_update_reminder":
		return handleCreateInitiativeUpdateReminder(args, transport)
	case "create_organization_from_onboarding":
		return handleCreateOrganizationFromOnboarding(args, transport)
	case "create_project_update_reminder":
		return handleCreateProjectUpdateReminder(args, transport)
	case "custom_view":
		return handleCustomView(args, transport)
	case "custom_view_create":
		return handleCustomViewCreate(args, transport)
	case "custom_view_delete":
		return handleCustomViewDelete(args, transport)
	case "custom_view_details_suggestion":
		return handleCustomViewDetailsSuggestion(args, transport)
	case "custom_view_has_subscribers":
		return handleCustomViewHasSubscribers(args, transport)
	case "custom_view_update":
		return handleCustomViewUpdate(args, transport)
	case "custom_views":
		return handleCustomViews(args, transport)
	case "customer":
		return handleCustomer(args, transport)
	case "customer_create":
		return handleCustomerCreate(args, transport)
	case "customer_delete":
		return handleCustomerDelete(args, transport)
	case "customer_merge":
		return handleCustomerMerge(args, transport)
	case "customer_need":
		return handleCustomerNeed(args, transport)
	case "customer_need_archive":
		return handleCustomerNeedArchive(args, transport)
	case "customer_need_create":
		return handleCustomerNeedCreate(args, transport)
	case "customer_need_create_from_attachment":
		return handleCustomerNeedCreateFromAttachment(args, transport)
	case "customer_need_delete":
		return handleCustomerNeedDelete(args, transport)
	case "customer_need_unarchive":
		return handleCustomerNeedUnarchive(args, transport)
	case "customer_need_update":
		return handleCustomerNeedUpdate(args, transport)
	case "customer_needs":
		return handleCustomerNeeds(args, transport)
	case "customer_status":
		return handleCustomerStatus(args, transport)
	case "customer_status_create":
		return handleCustomerStatusCreate(args, transport)
	case "customer_status_delete":
		return handleCustomerStatusDelete(args, transport)
	case "customer_status_update":
		return handleCustomerStatusUpdate(args, transport)
	case "customer_statuses":
		return handleCustomerStatuses(args, transport)
	case "customer_tier":
		return handleCustomerTier(args, transport)
	case "customer_tier_create":
		return handleCustomerTierCreate(args, transport)
	case "customer_tier_delete":
		return handleCustomerTierDelete(args, transport)
	case "customer_tier_update":
		return handleCustomerTierUpdate(args, transport)
	case "customer_tiers":
		return handleCustomerTiers(args, transport)
	case "customer_unsync":
		return handleCustomerUnsync(args, transport)
	case "customer_update":
		return handleCustomerUpdate(args, transport)
	case "customer_upsert":
		return handleCustomerUpsert(args, transport)
	case "customers":
		return handleCustomers(args, transport)
	case "cycle":
		return handleCycle(args, transport)
	case "cycle_archive":
		return handleCycleArchive(args, transport)
	case "cycle_archived":
		return handleCycleArchived(args, transport)
	case "cycle_create":
		return handleCycleCreate(args, transport)
	case "cycle_created":
		return handleCycleCreated(args, transport)
	case "cycle_shift_all":
		return handleCycleShiftAll(args, transport)
	case "cycle_start_upcoming_cycle_today":
		return handleCycleStartUpcomingCycleToday(args, transport)
	case "cycle_update":
		return handleCycleUpdate(args, transport)
	case "cycle_updated":
		return handleCycleUpdated(args, transport)
	case "cycles":
		return handleCycles(args, transport)
	case "document":
		return handleDocument(args, transport)
	case "document_archived":
		return handleDocumentArchived(args, transport)
	case "document_content_created":
		return handleDocumentContentCreated(args, transport)
	case "document_content_draft_created":
		return handleDocumentContentDraftCreated(args, transport)
	case "document_content_draft_deleted":
		return handleDocumentContentDraftDeleted(args, transport)
	case "document_content_draft_updated":
		return handleDocumentContentDraftUpdated(args, transport)
	case "document_content_history":
		return handleDocumentContentHistory(args, transport)
	case "document_content_history_entries":
		return handleDocumentContentHistoryEntries(args, transport)
	case "document_content_history_timeline":
		return handleDocumentContentHistoryTimeline(args, transport)
	case "document_content_updated":
		return handleDocumentContentUpdated(args, transport)
	case "document_create":
		return handleDocumentCreate(args, transport)
	case "document_created":
		return handleDocumentCreated(args, transport)
	case "document_delete":
		return handleDocumentDelete(args, transport)
	case "document_unarchive":
		return handleDocumentUnarchive(args, transport)
	case "document_unarchived":
		return handleDocumentUnarchived(args, transport)
	case "document_update":
		return handleDocumentUpdate(args, transport)
	case "document_updated":
		return handleDocumentUpdated(args, transport)
	case "documents":
		return handleDocuments(args, transport)
	case "draft_created":
		return handleDraftCreated(args, transport)
	case "draft_deleted":
		return handleDraftDeleted(args, transport)
	case "draft_updated":
		return handleDraftUpdated(args, transport)
	case "dummy":
		return handle_dummy(args, transport)
	case "email_intake_address":
		return handleEmailIntakeAddress(args, transport)
	case "email_intake_address_create":
		return handleEmailIntakeAddressCreate(args, transport)
	case "email_intake_address_delete":
		return handleEmailIntakeAddressDelete(args, transport)
	case "email_intake_address_rotate":
		return handleEmailIntakeAddressRotate(args, transport)
	case "email_intake_address_update":
		return handleEmailIntakeAddressUpdate(args, transport)
	case "email_token_user_account_auth":
		return handleEmailTokenUserAccountAuth(args, transport)
	case "email_unsubscribe":
		return handleEmailUnsubscribe(args, transport)
	case "email_user_account_auth_challenge":
		return handleEmailUserAccountAuthChallenge(args, transport)
	case "emoji":
		return handleEmoji(args, transport)
	case "emoji_create":
		return handleEmojiCreate(args, transport)
	case "emoji_delete":
		return handleEmojiDelete(args, transport)
	case "emojis":
		return handleEmojis(args, transport)
	case "entity_external_link":
		return handleEntityExternalLink(args, transport)
	case "entity_external_link_create":
		return handleEntityExternalLinkCreate(args, transport)
	case "entity_external_link_delete":
		return handleEntityExternalLinkDelete(args, transport)
	case "entity_external_link_update":
		return handleEntityExternalLinkUpdate(args, transport)
	case "external_user":
		return handleExternalUser(args, transport)
	case "external_users":
		return handleExternalUsers(args, transport)
	case "failures_for_oauth_webhooks":
		return handleFailuresForOauthWebhooks(args, transport)
	case "favorite":
		return handleFavorite(args, transport)
	case "favorite_create":
		return handleFavoriteCreate(args, transport)
	case "favorite_created":
		return handleFavoriteCreated(args, transport)
	case "favorite_delete":
		return handleFavoriteDelete(args, transport)
	case "favorite_deleted":
		return handleFavoriteDeleted(args, transport)
	case "favorite_update":
		return handleFavoriteUpdate(args, transport)
	case "favorite_updated":
		return handleFavoriteUpdated(args, transport)
	case "favorites":
		return handleFavorites(args, transport)
	case "fetch_data":
		return handleFetchData(args, transport)
	case "file_upload":
		return handleFileUpload(args, transport)
	case "file_upload_dangerously_delete":
		return handleFileUploadDangerouslyDelete(args, transport)
	case "git_automation_state_create":
		return handleGitAutomationStateCreate(args, transport)
	case "git_automation_state_delete":
		return handleGitAutomationStateDelete(args, transport)
	case "git_automation_state_update":
		return handleGitAutomationStateUpdate(args, transport)
	case "git_automation_target_branch_create":
		return handleGitAutomationTargetBranchCreate(args, transport)
	case "git_automation_target_branch_delete":
		return handleGitAutomationTargetBranchDelete(args, transport)
	case "git_automation_target_branch_update":
		return handleGitAutomationTargetBranchUpdate(args, transport)
	case "google_user_account_auth":
		return handleGoogleUserAccountAuth(args, transport)
	case "image_upload_from_url":
		return handleImageUploadFromUrl(args, transport)
	case "import_file_upload":
		return handleImportFileUpload(args, transport)
	case "initiative":
		return handleInitiative(args, transport)
	case "initiative_add_label":
		return handleInitiativeAddLabel(args, transport)
	case "initiative_archive":
		return handleInitiativeArchive(args, transport)
	case "initiative_create":
		return handleInitiativeCreate(args, transport)
	case "initiative_created":
		return handleInitiativeCreated(args, transport)
	case "initiative_delete":
		return handleInitiativeDelete(args, transport)
	case "initiative_deleted":
		return handleInitiativeDeleted(args, transport)
	case "initiative_relation":
		return handleInitiativeRelation(args, transport)
	case "initiative_relation_create":
		return handleInitiativeRelationCreate(args, transport)
	case "initiative_relation_delete":
		return handleInitiativeRelationDelete(args, transport)
	case "initiative_relation_update":
		return handleInitiativeRelationUpdate(args, transport)
	case "initiative_relations":
		return handleInitiativeRelations(args, transport)
	case "initiative_remove_label":
		return handleInitiativeRemoveLabel(args, transport)
	case "initiative_to_project":
		return handleInitiativeToProject(args, transport)
	case "initiative_to_project_create":
		return handleInitiativeToProjectCreate(args, transport)
	case "initiative_to_project_delete":
		return handleInitiativeToProjectDelete(args, transport)
	case "initiative_to_project_update":
		return handleInitiativeToProjectUpdate(args, transport)
	case "initiative_to_projects":
		return handleInitiativeToProjects(args, transport)
	case "initiative_unarchive":
		return handleInitiativeUnarchive(args, transport)
	case "initiative_update":
		return handleInitiativeUpdate(args, transport)
	case "initiative_update_archive":
		return handleInitiativeUpdateArchive(args, transport)
	case "initiative_update_create":
		return handleInitiativeUpdateCreate(args, transport)
	case "initiative_update_mutation":
		return handleInitiativeUpdateMutation(args, transport)
	case "initiative_update_unarchive":
		return handleInitiativeUpdateUnarchive(args, transport)
	case "initiative_update_update":
		return handleInitiativeUpdateUpdate(args, transport)
	case "initiative_updated":
		return handleInitiativeUpdated(args, transport)
	case "initiative_updates":
		return handleInitiativeUpdates(args, transport)
	case "initiatives":
		return handleInitiatives(args, transport)
	case "integration":
		return handleIntegration(args, transport)
	case "integration_archive":
		return handleIntegrationArchive(args, transport)
	case "integration_asks_connect_channel":
		return handleIntegrationAsksConnectChannel(args, transport)
	case "integration_customer_data_attributes_refresh":
		return handleIntegrationCustomerDataAttributesRefresh(args, transport)
	case "integration_delete":
		return handleIntegrationDelete(args, transport)
	case "integration_discord":
		return handleIntegrationDiscord(args, transport)
	case "integration_figma":
		return handleIntegrationFigma(args, transport)
	case "integration_front":
		return handleIntegrationFront(args, transport)
	case "integration_git_hub_enterprise_server_connect":
		return handleIntegrationGitHubEnterpriseServerConnect(args, transport)
	case "integration_git_hub_personal":
		return handleIntegrationGitHubPersonal(args, transport)
	case "integration_github_commit_create":
		return handleIntegrationGithubCommitCreate(args, transport)
	case "integration_github_connect":
		return handleIntegrationGithubConnect(args, transport)
	case "integration_github_import_connect":
		return handleIntegrationGithubImportConnect(args, transport)
	case "integration_github_import_refresh":
		return handleIntegrationGithubImportRefresh(args, transport)
	case "integration_github_remove_code_access":
		return handleIntegrationGithubRemoveCodeAccess(args, transport)
	case "integration_gitlab_connect":
		return handleIntegrationGitlabConnect(args, transport)
	case "integration_gitlab_test_connection":
		return handleIntegrationGitlabTestConnection(args, transport)
	case "integration_gong":
		return handleIntegrationGong(args, transport)
	case "integration_google_calendar_personal_connect":
		return handleIntegrationGoogleCalendarPersonalConnect(args, transport)
	case "integration_google_sheets":
		return handleIntegrationGoogleSheets(args, transport)
	case "integration_has_scopes":
		return handleIntegrationHasScopes(args, transport)
	case "integration_intercom":
		return handleIntegrationIntercom(args, transport)
	case "integration_intercom_delete":
		return handleIntegrationIntercomDelete(args, transport)
	case "integration_intercom_settings_update":
		return handleIntegrationIntercomSettingsUpdate(args, transport)
	case "integration_jira_fetch_project_statuses":
		return handleIntegrationJiraFetchProjectStatuses(args, transport)
	case "integration_jira_personal":
		return handleIntegrationJiraPersonal(args, transport)
	case "integration_jira_update":
		return handleIntegrationJiraUpdate(args, transport)
	case "integration_launch_darkly_connect":
		return handleIntegrationLaunchDarklyConnect(args, transport)
	case "integration_launch_darkly_personal_connect":
		return handleIntegrationLaunchDarklyPersonalConnect(args, transport)
	case "integration_loom":
		return handleIntegrationLoom(args, transport)
	case "integration_mcp_server_connect":
		return handleIntegrationMcpServerConnect(args, transport)
	case "integration_mcp_server_personal_connect":
		return handleIntegrationMcpServerPersonalConnect(args, transport)
	case "integration_microsoft_personal_connect":
		return handleIntegrationMicrosoftPersonalConnect(args, transport)
	case "integration_microsoft_teams":
		return handleIntegrationMicrosoftTeams(args, transport)
	case "integration_microsoft_teams_project_post":
		return handleIntegrationMicrosoftTeamsProjectPost(args, transport)
	case "integration_opsgenie_connect":
		return handleIntegrationOpsgenieConnect(args, transport)
	case "integration_opsgenie_refresh_schedule_mappings":
		return handleIntegrationOpsgenieRefreshScheduleMappings(args, transport)
	case "integration_pager_duty_connect":
		return handleIntegrationPagerDutyConnect(args, transport)
	case "integration_pager_duty_refresh_schedule_mappings":
		return handleIntegrationPagerDutyRefreshScheduleMappings(args, transport)
	case "integration_request":
		return handleIntegrationRequest(args, transport)
	case "integration_salesforce":
		return handleIntegrationSalesforce(args, transport)
	case "integration_salesforce_metadata_refresh":
		return handleIntegrationSalesforceMetadataRefresh(args, transport)
	case "integration_sentry_connect":
		return handleIntegrationSentryConnect(args, transport)
	case "integration_settings_update":
		return handleIntegrationSettingsUpdate(args, transport)
	case "integration_slack":
		return handleIntegrationSlack(args, transport)
	case "integration_slack_asks":
		return handleIntegrationSlackAsks(args, transport)
	case "integration_slack_custom_view_notifications":
		return handleIntegrationSlackCustomViewNotifications(args, transport)
	case "integration_slack_customer_channel_link":
		return handleIntegrationSlackCustomerChannelLink(args, transport)
	case "integration_slack_import_emojis":
		return handleIntegrationSlackImportEmojis(args, transport)
	case "integration_slack_initiative_post":
		return handleIntegrationSlackInitiativePost(args, transport)
	case "integration_slack_or_asks_update_slack_team_name":
		return handleIntegrationSlackOrAsksUpdateSlackTeamName(args, transport)
	case "integration_slack_org_initiative_updates_post":
		return handleIntegrationSlackOrgInitiativeUpdatesPost(args, transport)
	case "integration_slack_org_project_updates_post":
		return handleIntegrationSlackOrgProjectUpdatesPost(args, transport)
	case "integration_slack_personal":
		return handleIntegrationSlackPersonal(args, transport)
	case "integration_slack_post":
		return handleIntegrationSlackPost(args, transport)
	case "integration_slack_project_post":
		return handleIntegrationSlackProjectPost(args, transport)
	case "integration_slack_workflow_access_update":
		return handleIntegrationSlackWorkflowAccessUpdate(args, transport)
	case "integration_template":
		return handleIntegrationTemplate(args, transport)
	case "integration_template_create":
		return handleIntegrationTemplateCreate(args, transport)
	case "integration_template_delete":
		return handleIntegrationTemplateDelete(args, transport)
	case "integration_templates":
		return handleIntegrationTemplates(args, transport)
	case "integration_update":
		return handleIntegrationUpdate(args, transport)
	case "integration_zendesk":
		return handleIntegrationZendesk(args, transport)
	case "integrations":
		return handleIntegrations(args, transport)
	case "integrations_settings":
		return handleIntegrationsSettings(args, transport)
	case "integrations_settings_create":
		return handleIntegrationsSettingsCreate(args, transport)
	case "integrations_settings_update":
		return handleIntegrationsSettingsUpdate(args, transport)
	case "issue":
		return handleIssue(args, transport)
	case "issue_add_label":
		return handleIssueAddLabel(args, transport)
	case "issue_archive":
		return handleIssueArchive(args, transport)
	case "issue_archived":
		return handleIssueArchived(args, transport)
	case "issue_batch_create":
		return handleIssueBatchCreate(args, transport)
	case "issue_batch_update":
		return handleIssueBatchUpdate(args, transport)
	case "issue_create":
		return handleIssueCreate(args, transport)
	case "issue_created":
		return handleIssueCreated(args, transport)
	case "issue_delete":
		return handleIssueDelete(args, transport)
	case "issue_description_update_from_front":
		return handleIssueDescriptionUpdateFromFront(args, transport)
	case "issue_draft_created":
		return handleIssueDraftCreated(args, transport)
	case "issue_draft_deleted":
		return handleIssueDraftDeleted(args, transport)
	case "issue_draft_updated":
		return handleIssueDraftUpdated(args, transport)
	case "issue_external_sync_disable":
		return handleIssueExternalSyncDisable(args, transport)
	case "issue_figma_file_key_search":
		return handleIssueFigmaFileKeySearch(args, transport)
	case "issue_filter_suggestion":
		return handleIssueFilterSuggestion(args, transport)
	case "issue_history_created":
		return handleIssueHistoryCreated(args, transport)
	case "issue_history_updated":
		return handleIssueHistoryUpdated(args, transport)
	case "issue_import_check_c_s_v":
		return handleIssueImportCheckCSV(args, transport)
	case "issue_import_check_sync":
		return handleIssueImportCheckSync(args, transport)
	case "issue_import_create_asana":
		return handleIssueImportCreateAsana(args, transport)
	case "issue_import_create_c_s_v_jira":
		return handleIssueImportCreateCSVJira(args, transport)
	case "issue_import_create_clubhouse":
		return handleIssueImportCreateClubhouse(args, transport)
	case "issue_import_create_github":
		return handleIssueImportCreateGithub(args, transport)
	case "issue_import_create_jira":
		return handleIssueImportCreateJira(args, transport)
	case "issue_import_create_linear_v2":
		return handleIssueImportCreateLinearV2(args, transport)
	case "issue_import_delete":
		return handleIssueImportDelete(args, transport)
	case "issue_import_jql_check":
		return handleIssueImportJqlCheck(args, transport)
	case "issue_import_process":
		return handleIssueImportProcess(args, transport)
	case "issue_import_update":
		return handleIssueImportUpdate(args, transport)
	case "issue_label":
		return handleIssueLabel(args, transport)
	case "issue_label_create":
		return handleIssueLabelCreate(args, transport)
	case "issue_label_created":
		return handleIssueLabelCreated(args, transport)
	case "issue_label_delete":
		return handleIssueLabelDelete(args, transport)
	case "issue_label_deleted":
		return handleIssueLabelDeleted(args, transport)
	case "issue_label_restore":
		return handleIssueLabelRestore(args, transport)
	case "issue_label_retire":
		return handleIssueLabelRetire(args, transport)
	case "issue_label_update":
		return handleIssueLabelUpdate(args, transport)
	case "issue_label_updated":
		return handleIssueLabelUpdated(args, transport)
	case "issue_labels":
		return handleIssueLabels(args, transport)
	case "issue_priority_values":
		return handleIssuePriorityValues(args, transport)
	case "issue_relation":
		return handleIssueRelation(args, transport)
	case "issue_relation_create":
		return handleIssueRelationCreate(args, transport)
	case "issue_relation_created":
		return handleIssueRelationCreated(args, transport)
	case "issue_relation_delete":
		return handleIssueRelationDelete(args, transport)
	case "issue_relation_deleted":
		return handleIssueRelationDeleted(args, transport)
	case "issue_relation_update":
		return handleIssueRelationUpdate(args, transport)
	case "issue_relation_updated":
		return handleIssueRelationUpdated(args, transport)
	case "issue_relations":
		return handleIssueRelations(args, transport)
	case "issue_reminder":
		return handleIssueReminder(args, transport)
	case "issue_remove_label":
		return handleIssueRemoveLabel(args, transport)
	case "issue_repository_suggestions":
		return handleIssueRepositorySuggestions(args, transport)
	case "issue_search":
		return handleIssueSearch(args, transport)
	case "issue_share":
		return handleIssueShare(args, transport)
	case "issue_subscribe":
		return handleIssueSubscribe(args, transport)
	case "issue_title_suggestion_from_customer_request":
		return handleIssueTitleSuggestionFromCustomerRequest(args, transport)
	case "issue_to_release":
		return handleIssueToRelease(args, transport)
	case "issue_to_release_create":
		return handleIssueToReleaseCreate(args, transport)
	case "issue_to_release_delete":
		return handleIssueToReleaseDelete(args, transport)
	case "issue_to_release_delete_by_issue_and_release":
		return handleIssueToReleaseDeleteByIssueAndRelease(args, transport)
	case "issue_to_releases":
		return handleIssueToReleases(args, transport)
	case "issue_unarchive":
		return handleIssueUnarchive(args, transport)
	case "issue_unarchived":
		return handleIssueUnarchived(args, transport)
	case "issue_unshare":
		return handleIssueUnshare(args, transport)
	case "issue_unsubscribe":
		return handleIssueUnsubscribe(args, transport)
	case "issue_update":
		return handleIssueUpdate(args, transport)
	case "issue_updated":
		return handleIssueUpdated(args, transport)
	case "issue_vcs_branch_search":
		return handleIssueVcsBranchSearch(args, transport)
	case "issues":
		return handleIssues(args, transport)
	case "jira_integration_connect":
		return handleJiraIntegrationConnect(args, transport)
	case "join_organization_from_onboarding":
		return handleJoinOrganizationFromOnboarding(args, transport)
	case "latest_release_by_access_key":
		return handleLatestReleaseByAccessKey(args, transport)
	case "leave_organization":
		return handleLeaveOrganization(args, transport)
	case "logout":
		return handleLogout(args, transport)
	case "logout_all_sessions":
		return handleLogoutAllSessions(args, transport)
	case "logout_other_sessions":
		return handleLogoutOtherSessions(args, transport)
	case "logout_session":
		return handleLogoutSession(args, transport)
	case "microsoft_teams_channels":
		return handleMicrosoftTeamsChannels(args, transport)
	case "notification":
		return handleNotification(args, transport)
	case "notification_archive":
		return handleNotificationArchive(args, transport)
	case "notification_archive_all":
		return handleNotificationArchiveAll(args, transport)
	case "notification_archived":
		return handleNotificationArchived(args, transport)
	case "notification_category_channel_subscription_update":
		return handleNotificationCategoryChannelSubscriptionUpdate(args, transport)
	case "notification_created":
		return handleNotificationCreated(args, transport)
	case "notification_deleted":
		return handleNotificationDeleted(args, transport)
	case "notification_mark_read_all":
		return handleNotificationMarkReadAll(args, transport)
	case "notification_mark_unread_all":
		return handleNotificationMarkUnreadAll(args, transport)
	case "notification_snooze_all":
		return handleNotificationSnoozeAll(args, transport)
	case "notification_subscription":
		return handleNotificationSubscription(args, transport)
	case "notification_subscription_create":
		return handleNotificationSubscriptionCreate(args, transport)
	case "notification_subscription_delete":
		return handleNotificationSubscriptionDelete(args, transport)
	case "notification_subscription_update":
		return handleNotificationSubscriptionUpdate(args, transport)
	case "notification_subscriptions":
		return handleNotificationSubscriptions(args, transport)
	case "notification_unarchive":
		return handleNotificationUnarchive(args, transport)
	case "notification_unarchived":
		return handleNotificationUnarchived(args, transport)
	case "notification_unsnooze_all":
		return handleNotificationUnsnoozeAll(args, transport)
	case "notification_update":
		return handleNotificationUpdate(args, transport)
	case "notification_updated":
		return handleNotificationUpdated(args, transport)
	case "notifications":
		return handleNotifications(args, transport)
	case "notifications_unread_count":
		return handleNotificationsUnreadCount(args, transport)
	case "oauth_application":
		return handleOauthApplication(args, transport)
	case "oauth_application_archive":
		return handleOauthApplicationArchive(args, transport)
	case "oauth_application_create":
		return handleOauthApplicationCreate(args, transport)
	case "oauth_application_rotate_secret":
		return handleOauthApplicationRotateSecret(args, transport)
	case "oauth_application_rotate_webhook_secret":
		return handleOauthApplicationRotateWebhookSecret(args, transport)
	case "oauth_application_update":
		return handleOauthApplicationUpdate(args, transport)
	case "oauth_applications":
		return handleOauthApplications(args, transport)
	case "organization":
		return handleOrganization(args, transport)
	case "organization_cancel_delete":
		return handleOrganizationCancelDelete(args, transport)
	case "organization_delete":
		return handleOrganizationDelete(args, transport)
	case "organization_delete_challenge":
		return handleOrganizationDeleteChallenge(args, transport)
	case "organization_domain_claim":
		return handleOrganizationDomainClaim(args, transport)
	case "organization_domain_claim_request":
		return handleOrganizationDomainClaimRequest(args, transport)
	case "organization_domain_create":
		return handleOrganizationDomainCreate(args, transport)
	case "organization_domain_delete":
		return handleOrganizationDomainDelete(args, transport)
	case "organization_domain_update":
		return handleOrganizationDomainUpdate(args, transport)
	case "organization_domain_verify":
		return handleOrganizationDomainVerify(args, transport)
	case "organization_exists":
		return handleOrganizationExists(args, transport)
	case "organization_invite":
		return handleOrganizationInvite(args, transport)
	case "organization_invite_create":
		return handleOrganizationInviteCreate(args, transport)
	case "organization_invite_delete":
		return handleOrganizationInviteDelete(args, transport)
	case "organization_invite_details":
		return handleOrganizationInviteDetails(args, transport)
	case "organization_invite_update":
		return handleOrganizationInviteUpdate(args, transport)
	case "organization_invites":
		return handleOrganizationInvites(args, transport)
	case "organization_meta":
		return handleOrganizationMeta(args, transport)
	case "organization_start_trial":
		return handleOrganizationStartTrial(args, transport)
	case "organization_start_trial_for_plan":
		return handleOrganizationStartTrialForPlan(args, transport)
	case "organization_update":
		return handleOrganizationUpdate(args, transport)
	case "organization_updated":
		return handleOrganizationUpdated(args, transport)
	case "passkey_login_finish":
		return handlePasskeyLoginFinish(args, transport)
	case "passkey_login_start":
		return handlePasskeyLoginStart(args, transport)
	case "project":
		return handleProject(args, transport)
	case "project_add_label":
		return handleProjectAddLabel(args, transport)
	case "project_archive":
		return handleProjectArchive(args, transport)
	case "project_archived":
		return handleProjectArchived(args, transport)
	case "project_create":
		return handleProjectCreate(args, transport)
	case "project_create_slack_channel":
		return handleProjectCreateSlackChannel(args, transport)
	case "project_created":
		return handleProjectCreated(args, transport)
	case "project_delete":
		return handleProjectDelete(args, transport)
	case "project_external_sync_disable":
		return handleProjectExternalSyncDisable(args, transport)
	case "project_filter_suggestion":
		return handleProjectFilterSuggestion(args, transport)
	case "project_label":
		return handleProjectLabel(args, transport)
	case "project_label_create":
		return handleProjectLabelCreate(args, transport)
	case "project_label_delete":
		return handleProjectLabelDelete(args, transport)
	case "project_label_restore":
		return handleProjectLabelRestore(args, transport)
	case "project_label_retire":
		return handleProjectLabelRetire(args, transport)
	case "project_label_update":
		return handleProjectLabelUpdate(args, transport)
	case "project_labels":
		return handleProjectLabels(args, transport)
	case "project_milestone":
		return handleProjectMilestone(args, transport)
	case "project_milestone_create":
		return handleProjectMilestoneCreate(args, transport)
	case "project_milestone_delete":
		return handleProjectMilestoneDelete(args, transport)
	case "project_milestone_move":
		return handleProjectMilestoneMove(args, transport)
	case "project_milestone_update":
		return handleProjectMilestoneUpdate(args, transport)
	case "project_milestones":
		return handleProjectMilestones(args, transport)
	case "project_reassign_status":
		return handleProjectReassignStatus(args, transport)
	case "project_relation":
		return handleProjectRelation(args, transport)
	case "project_relation_create":
		return handleProjectRelationCreate(args, transport)
	case "project_relation_delete":
		return handleProjectRelationDelete(args, transport)
	case "project_relation_update":
		return handleProjectRelationUpdate(args, transport)
	case "project_relations":
		return handleProjectRelations(args, transport)
	case "project_remove_label":
		return handleProjectRemoveLabel(args, transport)
	case "project_status":
		return handleProjectStatus(args, transport)
	case "project_status_archive":
		return handleProjectStatusArchive(args, transport)
	case "project_status_create":
		return handleProjectStatusCreate(args, transport)
	case "project_status_project_count":
		return handleProjectStatusProjectCount(args, transport)
	case "project_status_unarchive":
		return handleProjectStatusUnarchive(args, transport)
	case "project_status_update":
		return handleProjectStatusUpdate(args, transport)
	case "project_statuses":
		return handleProjectStatuses(args, transport)
	case "project_unarchive":
		return handleProjectUnarchive(args, transport)
	case "project_unarchived":
		return handleProjectUnarchived(args, transport)
	case "project_update":
		return handleProjectUpdate(args, transport)
	case "project_update_archive":
		return handleProjectUpdateArchive(args, transport)
	case "project_update_archived":
		return handleProjectUpdateArchived(args, transport)
	case "project_update_create":
		return handleProjectUpdateCreate(args, transport)
	case "project_update_created":
		return handleProjectUpdateCreated(args, transport)
	case "project_update_delete":
		return handleProjectUpdateDelete(args, transport)
	case "project_update_deleted":
		return handleProjectUpdateDeleted(args, transport)
	case "project_update_mutation":
		return handleProjectUpdateMutation(args, transport)
	case "project_update_unarchive":
		return handleProjectUpdateUnarchive(args, transport)
	case "project_update_update":
		return handleProjectUpdateUpdate(args, transport)
	case "project_update_updated":
		return handleProjectUpdateUpdated(args, transport)
	case "project_updated":
		return handleProjectUpdated(args, transport)
	case "project_updates":
		return handleProjectUpdates(args, transport)
	case "projects":
		return handleProjects(args, transport)
	case "push_subscription_create":
		return handlePushSubscriptionCreate(args, transport)
	case "push_subscription_delete":
		return handlePushSubscriptionDelete(args, transport)
	case "push_subscription_test":
		return handlePushSubscriptionTest(args, transport)
	case "rate_limit_status":
		return handleRateLimitStatus(args, transport)
	case "reaction_create":
		return handleReactionCreate(args, transport)
	case "reaction_delete":
		return handleReactionDelete(args, transport)
	case "recent_releases_by_access_key":
		return handleRecentReleasesByAccessKey(args, transport)
	case "refresh_google_sheets_data":
		return handleRefreshGoogleSheetsData(args, transport)
	case "release":
		return handleRelease(args, transport)
	case "release_archive":
		return handleReleaseArchive(args, transport)
	case "release_complete":
		return handleReleaseComplete(args, transport)
	case "release_complete_by_access_key":
		return handleReleaseCompleteByAccessKey(args, transport)
	case "release_create":
		return handleReleaseCreate(args, transport)
	case "release_delete":
		return handleReleaseDelete(args, transport)
	case "release_note":
		return handleReleaseNote(args, transport)
	case "release_note_create":
		return handleReleaseNoteCreate(args, transport)
	case "release_note_delete":
		return handleReleaseNoteDelete(args, transport)
	case "release_note_update":
		return handleReleaseNoteUpdate(args, transport)
	case "release_notes":
		return handleReleaseNotes(args, transport)
	case "release_pipeline":
		return handleReleasePipeline(args, transport)
	case "release_pipeline_archive":
		return handleReleasePipelineArchive(args, transport)
	case "release_pipeline_by_access_key":
		return handleReleasePipelineByAccessKey(args, transport)
	case "release_pipeline_create":
		return handleReleasePipelineCreate(args, transport)
	case "release_pipeline_delete":
		return handleReleasePipelineDelete(args, transport)
	case "release_pipeline_unarchive":
		return handleReleasePipelineUnarchive(args, transport)
	case "release_pipeline_update":
		return handleReleasePipelineUpdate(args, transport)
	case "release_pipelines":
		return handleReleasePipelines(args, transport)
	case "release_search":
		return handleReleaseSearch(args, transport)
	case "release_stage":
		return handleReleaseStage(args, transport)
	case "release_stage_archive":
		return handleReleaseStageArchive(args, transport)
	case "release_stage_create":
		return handleReleaseStageCreate(args, transport)
	case "release_stage_unarchive":
		return handleReleaseStageUnarchive(args, transport)
	case "release_stage_update":
		return handleReleaseStageUpdate(args, transport)
	case "release_stages":
		return handleReleaseStages(args, transport)
	case "release_sync":
		return handleReleaseSync(args, transport)
	case "release_sync_by_access_key":
		return handleReleaseSyncByAccessKey(args, transport)
	case "release_unarchive":
		return handleReleaseUnarchive(args, transport)
	case "release_update":
		return handleReleaseUpdate(args, transport)
	case "release_update_by_pipeline":
		return handleReleaseUpdateByPipeline(args, transport)
	case "release_update_by_pipeline_by_access_key":
		return handleReleaseUpdateByPipelineByAccessKey(args, transport)
	case "releases":
		return handleReleases(args, transport)
	case "resend_organization_invite":
		return handleResendOrganizationInvite(args, transport)
	case "resend_organization_invite_by_email":
		return handleResendOrganizationInviteByEmail(args, transport)
	case "roadmap":
		return handleRoadmap(args, transport)
	case "roadmap_archive":
		return handleRoadmapArchive(args, transport)
	case "roadmap_create":
		return handleRoadmapCreate(args, transport)
	case "roadmap_created":
		return handleRoadmapCreated(args, transport)
	case "roadmap_delete":
		return handleRoadmapDelete(args, transport)
	case "roadmap_deleted":
		return handleRoadmapDeleted(args, transport)
	case "roadmap_to_project":
		return handleRoadmapToProject(args, transport)
	case "roadmap_to_project_create":
		return handleRoadmapToProjectCreate(args, transport)
	case "roadmap_to_project_delete":
		return handleRoadmapToProjectDelete(args, transport)
	case "roadmap_to_project_update":
		return handleRoadmapToProjectUpdate(args, transport)
	case "roadmap_to_projects":
		return handleRoadmapToProjects(args, transport)
	case "roadmap_unarchive":
		return handleRoadmapUnarchive(args, transport)
	case "roadmap_update":
		return handleRoadmapUpdate(args, transport)
	case "roadmap_updated":
		return handleRoadmapUpdated(args, transport)
	case "roadmaps":
		return handleRoadmaps(args, transport)
	case "saml_token_user_account_auth":
		return handleSamlTokenUserAccountAuth(args, transport)
	case "search_documents":
		return handleSearchDocuments(args, transport)
	case "search_issues":
		return handleSearchIssues(args, transport)
	case "search_projects":
		return handleSearchProjects(args, transport)
	case "semantic_search":
		return handleSemanticSearch(args, transport)
	case "sla_configurations":
		return handleSlaConfigurations(args, transport)
	case "sso_url_from_email":
		return handleSsoUrlFromEmail(args, transport)
	case "team":
		return handleTeam(args, transport)
	case "team_create":
		return handleTeamCreate(args, transport)
	case "team_created":
		return handleTeamCreated(args, transport)
	case "team_cycles_delete":
		return handleTeamCyclesDelete(args, transport)
	case "team_delete":
		return handleTeamDelete(args, transport)
	case "team_deleted":
		return handleTeamDeleted(args, transport)
	case "team_key_delete":
		return handleTeamKeyDelete(args, transport)
	case "team_membership":
		return handleTeamMembership(args, transport)
	case "team_membership_create":
		return handleTeamMembershipCreate(args, transport)
	case "team_membership_created":
		return handleTeamMembershipCreated(args, transport)
	case "team_membership_delete":
		return handleTeamMembershipDelete(args, transport)
	case "team_membership_deleted":
		return handleTeamMembershipDeleted(args, transport)
	case "team_membership_update":
		return handleTeamMembershipUpdate(args, transport)
	case "team_membership_updated":
		return handleTeamMembershipUpdated(args, transport)
	case "team_memberships":
		return handleTeamMemberships(args, transport)
	case "team_unarchive":
		return handleTeamUnarchive(args, transport)
	case "team_update":
		return handleTeamUpdate(args, transport)
	case "team_updated":
		return handleTeamUpdated(args, transport)
	case "teams":
		return handleTeams(args, transport)
	case "template":
		return handleTemplate(args, transport)
	case "template_create":
		return handleTemplateCreate(args, transport)
	case "template_delete":
		return handleTemplateDelete(args, transport)
	case "template_update":
		return handleTemplateUpdate(args, transport)
	case "templates":
		return handleTemplates(args, transport)
	case "templates_for_integration":
		return handleTemplatesForIntegration(args, transport)
	case "time_schedule":
		return handleTimeSchedule(args, transport)
	case "time_schedule_create":
		return handleTimeScheduleCreate(args, transport)
	case "time_schedule_delete":
		return handleTimeScheduleDelete(args, transport)
	case "time_schedule_refresh_integration_schedule":
		return handleTimeScheduleRefreshIntegrationSchedule(args, transport)
	case "time_schedule_update":
		return handleTimeScheduleUpdate(args, transport)
	case "time_schedule_upsert_external":
		return handleTimeScheduleUpsertExternal(args, transport)
	case "time_schedules":
		return handleTimeSchedules(args, transport)
	case "track_anonymous_event":
		return handleTrackAnonymousEvent(args, transport)
	case "triage_responsibilities":
		return handleTriageResponsibilities(args, transport)
	case "triage_responsibility":
		return handleTriageResponsibility(args, transport)
	case "triage_responsibility_create":
		return handleTriageResponsibilityCreate(args, transport)
	case "triage_responsibility_delete":
		return handleTriageResponsibilityDelete(args, transport)
	case "triage_responsibility_update":
		return handleTriageResponsibilityUpdate(args, transport)
	case "update_integration_slack_scopes":
		return handleUpdateIntegrationSlackScopes(args, transport)
	case "user":
		return handleUser(args, transport)
	case "user_change_role":
		return handleUserChangeRole(args, transport)
	case "user_created":
		return handleUserCreated(args, transport)
	case "user_discord_connect":
		return handleUserDiscordConnect(args, transport)
	case "user_external_user_disconnect":
		return handleUserExternalUserDisconnect(args, transport)
	case "user_flag_update":
		return handleUserFlagUpdate(args, transport)
	case "user_revoke_all_sessions":
		return handleUserRevokeAllSessions(args, transport)
	case "user_revoke_session":
		return handleUserRevokeSession(args, transport)
	case "user_sessions":
		return handleUserSessions(args, transport)
	case "user_settings":
		return handleUserSettings(args, transport)
	case "user_settings_flags_reset":
		return handleUserSettingsFlagsReset(args, transport)
	case "user_settings_update":
		return handleUserSettingsUpdate(args, transport)
	case "user_suspend":
		return handleUserSuspend(args, transport)
	case "user_unlink_from_identity_provider":
		return handleUserUnlinkFromIdentityProvider(args, transport)
	case "user_unsuspend":
		return handleUserUnsuspend(args, transport)
	case "user_update":
		return handleUserUpdate(args, transport)
	case "user_updated":
		return handleUserUpdated(args, transport)
	case "users":
		return handleUsers(args, transport)
	case "verify_git_hub_enterprise_server_installation":
		return handleVerifyGitHubEnterpriseServerInstallation(args, transport)
	case "view_preferences_create":
		return handleViewPreferencesCreate(args, transport)
	case "view_preferences_delete":
		return handleViewPreferencesDelete(args, transport)
	case "view_preferences_update":
		return handleViewPreferencesUpdate(args, transport)
	case "viewer":
		return handleViewer(args, transport)
	case "webhook":
		return handleWebhook(args, transport)
	case "webhook_create":
		return handleWebhookCreate(args, transport)
	case "webhook_delete":
		return handleWebhookDelete(args, transport)
	case "webhook_rotate_secret":
		return handleWebhookRotateSecret(args, transport)
	case "webhook_update":
		return handleWebhookUpdate(args, transport)
	case "webhooks":
		return handleWebhooks(args, transport)
	case "workflow_state":
		return handleWorkflowState(args, transport)
	case "workflow_state_archive":
		return handleWorkflowStateArchive(args, transport)
	case "workflow_state_archived":
		return handleWorkflowStateArchived(args, transport)
	case "workflow_state_create":
		return handleWorkflowStateCreate(args, transport)
	case "workflow_state_created":
		return handleWorkflowStateCreated(args, transport)
	case "workflow_state_update":
		return handleWorkflowStateUpdate(args, transport)
	case "workflow_state_updated":
		return handleWorkflowStateUpdated(args, transport)
	case "workflow_states":
		return handleWorkflowStates(args, transport)
	}
	return nil, fmt.Errorf("unhandled op %q", op)
}

func writeError(w io.Writer, class, message string) {
	out := output{Error: &outputError{Class: class, Message: message}}
	_ = json.NewEncoder(w).Encode(out)
}

func writeSuccess(w io.Writer, payload map[string]any) {
	out := output{Output: payload}
	_ = json.NewEncoder(w).Encode(out)
}

// classify maps a handler error into the Aileron error class string.
// Non-GraphQL errors funnel to `connector_runtime_error`; a
// `*graphqlErrors` (HTTP 200 with non-empty errors[]) gets its
// own class so callers can distinguish.
func classify(err error) string {
	var graphqlErr *graphqlErrors
	if errors.As(err, &graphqlErr) {
		return "graphql_error"
	}
	return "connector_runtime_error"
}
